# PlatformIO extra_script: generate src/CasterSecrets.h from the fleet files.
#
# Single source of truth for per-unit configuration:
#   tools/known-boards.txt    (committed)  CP2104 serial -> assembly label
#   tools/fleet-secrets.ini   (gitignored) caster credentials + per-assembly secrets
#
# The WiFi SSID equals the assembly label (name the phone hotspot after the unit)
# unless the assembly's section sets wifi_ssid. The BLE name also defaults to the
# assembly label, unless the assembly's section sets ble_name.
# Result: one identity per unit: sticker, hotspot and BLE all match.
# BLE names must be unique across the fleet and fit the scan response (max 29
# bytes); both are checked here. An empty kBleName (placeholder builds) falls
# back to rtkrover-<chip-id> name at runtime (getDeviceName).
#
# Assembly selection, in order:
#   1. RTK_BOARD env var (CP2104 serial): flash.sh exports this
#   2. exactly one known ESP32 board attached over USB
#   3. otherwise the previously generated header is kept as-is, so builds
#      without hardware stay possible; a fresh clone gets an empty placeholder.
# Incomplete secrets for the selected assembly are a hard error when the board
# was requested explicitly.
import configparser
import os
import sys

from SCons.Script import COMMAND_LINE_TARGETS

Import("env")  # noqa: F821 -- provided by PlatformIO/SCons

PROJECT_DIR = env["PROJECT_DIR"]  # noqa: F821
HEADER = os.path.join(PROJECT_DIR, "src", "CasterSecrets.h")
BOARDS_FILE = os.path.join(PROJECT_DIR, "tools", "known-boards.txt")
SECRETS_FILE = os.path.join(PROJECT_DIR, "tools", "fleet-secrets.ini")

# The BLE name is carried in the 31-byte scan response as a
# Complete Local Name TLV (2 bytes overhead).
BLE_NAME_MAX = 29


def fail(msg):
    sys.stderr.write("gen_caster_secrets: ERROR: %s\n" % msg)
    env.Exit(1)  # noqa: F821
    raise SystemExit(1)  # env.Exit only flags; stop this script now


def read_known_boards():
    boards = []  # [(serial, label)]
    with open(BOARDS_FILE) as f:
        for line in f:
            line = line.split("#", 1)[0].strip()
            if not line:
                continue
            parts = line.split()
            if len(parts) >= 2:
                boards.append((parts[0], parts[1]))
    return boards


def attached_boards(boards):
    return [(s, l) for s, l in boards if os.path.exists("/dev/cu.usbserial-" + s)]


def select_label(boards):
    """Return (label, None) or (None, reason-string)."""
    want = os.environ.get("RTK_BOARD", "").strip()
    if want:
        for serial, label in boards:
            if want in (serial, label):
                return label, None
        fail(
            "RTK_BOARD='%s' is not a known unit in tools/known-boards.txt" % want
        )
    attached = attached_boards(boards)
    if len(attached) == 1:
        return attached[0][1], None
    if len(attached) > 1:
        return None, "multiple known boards attached (set RTK_BOARD to pick one)"
    return None, "no known board attached and RTK_BOARD not set"


def c_escape(s):
    return s.replace("\\", "\\\\").replace('"', '\\"')


def render(board_line, values):
    lines = [
        "// Auto-generated by tools/gen_caster_secrets.py at build time. Do not",
        "// edit; gitignored. Sources: tools/known-boards.txt (committed) +",
        "// tools/fleet-secrets.ini (gitignored; see fleet-secrets_example.ini).",
        "// board: %s" % board_line,
        "#ifndef CASTER_SECRETS_H",
        "#define CASTER_SECRETS_H",
        "",
    ]
    for name, value in values:
        lines.append('const char %s[] = "%s";' % (name, c_escape(value)))
    lines += ["", "#endif /*** CASTER_SECRETS_H ***/", ""]
    return "\n".join(lines)


def write_if_changed(content):
    previous = None
    if os.path.isfile(HEADER):
        with open(HEADER) as f:
            previous = f.read()
    if content != previous:
        with open(HEADER, "w") as f:
            f.write(content)


def existing_header_board():
    if not os.path.isfile(HEADER):
        return None
    with open(HEADER) as f:
        for line in f:
            if line.startswith("// board: "):
                return line[len("// board: "):].strip()
    return "(hand-written, pre-generator)"


def migrate_kept_header():
    """Add constants that post-date a kept header, so it still compiles."""
    with open(HEADER) as f:
        content = f.read()
    if "kBleName" in content:
        return
    addition = (
        '// added by generator migration: empty = chip-id BLE name fallback\n'
        'const char kBleName[] = "";\n'
    )
    marker = "\n#endif"
    if marker not in content:
        return
    with open(HEADER, "w") as f:
        f.write(content.replace(marker, "\n" + addition + marker, 1))
    print("gen_caster_secrets: added missing kBleName to kept header")


def keep_or_placeholder(reason):
    kept = existing_header_board()
    if kept is not None:
        print(
            "gen_caster_secrets: %s; keeping existing src/CasterSecrets.h "
            "(board: %s)" % (reason, kept)
        )
        migrate_kept_header()
        return
    print(
        "gen_caster_secrets: WARNING: %s and no existing header; writing "
        "empty placeholder. This build cannot reach WiFi or the caster -- "
        "set RTK_BOARD or attach a unit before flashing." % reason
    )
    names = [
        "kCasterHost", "kCasterPort", "kMountPoint", "kCasterUser",
        "kCasterPass", "kWifiSsid", "kWifiPw", "kBleName",
    ]
    write_if_changed(render("(none -- placeholder)", [(n, "") for n in names]))


def main():
    if not os.path.isfile(BOARDS_FILE):
        fail("missing %s" % BOARDS_FILE)
    boards = read_known_boards()

    if not os.path.isfile(SECRETS_FILE):
        keep_or_placeholder("tools/fleet-secrets.ini not found")
        return

    label, reason = select_label(boards)
    if label is None:
        keep_or_placeholder(reason)
        return

    cfg = configparser.ConfigParser()
    cfg.read(SECRETS_FILE)

    if not cfg.has_section("caster"):
        fail("%s has no [caster] section" % SECRETS_FILE)

    # Incomplete secrets for the selected board are fatal when the choice was
    # explicit (RTK_BOARD) or the firmware is about to be flashed.
    # For a plain build with the board merely auto-detected over USB, fall back
    # like "no board selected".
    explicit = bool(os.environ.get("RTK_BOARD", "").strip())
    strict = explicit or ("upload" in COMMAND_LINE_TARGETS)

    def incomplete(msg):
        if strict:
            fail(msg)
        keep_or_placeholder(msg + " (not uploading, so building anyway)")

    if not cfg.has_section(label):
        incomplete(
            "%s has no [%s] section for the selected board" % (SECRETS_FILE, label)
        )
        return
    board = cfg[label]

    missing = []

    def caster(key):
        # per-board caster_<key> overrides the shared [caster] value
        value = board.get("caster_" + key, cfg["caster"].get(key))
        if value is None:
            missing.append("caster '%s'" % key)
            return ""
        return value

    wifi_pw = board.get("wifi_pw")
    if wifi_pw is None:
        missing.append("wifi_pw")
        wifi_pw = ""
    wifi_ssid = board.get("wifi_ssid", label)

    # BLE name: assembly label unless overridden.
    # Validate fleet-wide (a duplicate makes two units indistinguishable).
    ble_names = {}
    for section in cfg.sections():
        if section == "caster":
            continue
        name = cfg[section].get("ble_name", section).strip()
        if not name:
            fail("[%s] in %s has an empty ble_name" % (section, SECRETS_FILE))
        if len(name.encode("utf-8")) > BLE_NAME_MAX:
            fail(
                "[%s] ble_name '%s' exceeds %d bytes (BLE scan response limit)"
                % (section, name, BLE_NAME_MAX)
            )
        if name in ble_names:
            fail(
                "duplicate BLE name '%s' for [%s] and [%s] in %s"
                % (name, ble_names[name], section, SECRETS_FILE)
            )
        ble_names[name] = section
    ble_name = cfg[label].get("ble_name", label).strip()

    values = [
        ("kCasterHost", caster("host")),
        ("kCasterPort", caster("port")),
        ("kMountPoint", caster("mount")),
        ("kCasterUser", caster("user")),
        ("kCasterPass", caster("pass")),
        ("kWifiSsid", wifi_ssid),
        ("kWifiPw", wifi_pw),
        ("kBleName", ble_name),
    ]
    if missing:
        incomplete(
            "[%s] in %s is missing: %s"
            % (label, SECRETS_FILE, ", ".join(missing))
        )
        return
    write_if_changed(render(label, values))
    print(
        "gen_caster_secrets: src/CasterSecrets.h for %s (ssid: %s, ble: %s, "
        "caster user: %s)" % (label, wifi_ssid, ble_name, values[3][1])
    )


main()
