# PlatformIO extra_script: generate src/AssemblyConfig.h (the BLE name) for
# the selected assembly.
#
# Since ADR-001 the firmware embeds no secrets: the caster credentials live in
# RWA Player and the phone's hotspot is not used. The one per-assembly fact
# left in the image is the BLE name, which is the assembly label from the
# committed
#   tools/known-boards.txt      CP2104 serial -> assembly label
# unless tools/fleet-secrets.ini (gitignored, optional) overrides it with a
# ble_name key in the assembly's section. ADR-002 moves the name into NVS
# and retires this script.
#
# BLE names must be unique across the fleet and fit the scan response (max 29
# bytes); both are checked here. An empty kBleName (placeholder builds) falls
# back to rtkrover-<chip-id> at runtime (getBleName in main.cpp).
#
# Assembly selection, in order:
#   1. RTK_BOARD env var (label or CP2104 serial): flash.sh exports this
#   2. exactly one known ESP32 board attached over USB
#   3. otherwise the previously generated header is kept as-is, so builds
#      without hardware stay possible; a fresh clone gets an empty placeholder.
import configparser
import os
import sys

Import("env")  # noqa: F821 -- provided by PlatformIO/SCons

PROJECT_DIR = env["PROJECT_DIR"]  # noqa: F821
HEADER = os.path.join(PROJECT_DIR, "src", "AssemblyConfig.h")
BOARDS_FILE = os.path.join(PROJECT_DIR, "tools", "known-boards.txt")
OVERRIDES_FILE = os.path.join(PROJECT_DIR, "tools", "fleet-secrets.ini")

# The BLE name is carried in the 31-byte scan response as a
# Complete Local Name TLV (2 bytes overhead).
BLE_NAME_MAX = 29


def fail(msg):
    sys.stderr.write("gen_assembly_config: ERROR: %s\n" % msg)
    env.Exit(1)  # noqa: F821
    raise SystemExit(1)  # env.Exit only flags; stop this script now


def read_known_boards():
    boards = []  # [(serial, label)]
    with open(BOARDS_FILE) as f:
        for line in f:
            line = line.split("#", 1)[0].strip()
            if not line:
                continue
            parts = line.split()
            if len(parts) >= 2:
                boards.append((parts[0], parts[1]))
    return boards


def read_name_overrides():
    """{assembly label: ble_name} from the optional fleet ini."""
    if not os.path.isfile(OVERRIDES_FILE):
        return {}
    cfg = configparser.ConfigParser()
    cfg.read(OVERRIDES_FILE)
    overrides = {}
    for section in cfg.sections():
        if section == "caster":
            continue
        name = cfg[section].get("ble_name")
        if name is not None:
            overrides[section] = name.strip()
    return overrides


def attached_boards(boards):
    return [(s, l) for s, l in boards if os.path.exists("/dev/cu.usbserial-" + s)]


def select_label(boards):
    """Return (label, None) or (None, reason-string)."""
    want = os.environ.get("RTK_BOARD", "").strip()
    if want:
        for serial, label in boards:
            if want in (serial, label):
                return label, None
        fail(
            "RTK_BOARD='%s' is not a known board in tools/known-boards.txt" % want
        )
    attached = attached_boards(boards)
    if len(attached) == 1:
        return attached[0][1], None
    if len(attached) > 1:
        return None, "multiple known boards attached (set RTK_BOARD to pick one)"
    return None, "no known board attached and RTK_BOARD not set"


def c_escape(s):
    return s.replace("\\", "\\\\").replace('"', '\\"')


def render(board_line, ble_name):
    return "\n".join([
        "// Auto-generated by tools/gen_assembly_config.py at build time. Do not",
        "// edit; gitignored. Sources: tools/known-boards.txt (committed) +",
        "// tools/fleet-secrets.ini (gitignored, optional ble_name override).",
        "// board: %s" % board_line,
        "#ifndef ASSEMBLY_CONFIG_H",
        "#define ASSEMBLY_CONFIG_H",
        "",
        "// The advertised BLE name; empty = rtkrover-<chip-id> fallback at runtime.",
        'const char kBleName[] = "%s";' % c_escape(ble_name),
        "",
        "#endif /*** ASSEMBLY_CONFIG_H ***/",
        "",
    ])


def write_if_changed(content):
    previous = None
    if os.path.isfile(HEADER):
        with open(HEADER) as f:
            previous = f.read()
    if content != previous:
        with open(HEADER, "w") as f:
            f.write(content)


def existing_header_board():
    if not os.path.isfile(HEADER):
        return None
    with open(HEADER) as f:
        for line in f:
            if line.startswith("// board: "):
                return line[len("// board: "):].strip()
    return "(unknown)"


def keep_or_placeholder(reason):
    kept = existing_header_board()
    if kept is not None:
        print(
            "gen_assembly_config: %s; keeping existing src/AssemblyConfig.h "
            "(board: %s)" % (reason, kept)
        )
        return
    print(
        "gen_assembly_config: WARNING: %s and no existing header; writing an "
        "empty placeholder (BLE name rtkrover-<chip-id>). Set RTK_BOARD or "
        "attach a known board to build a named image." % reason
    )
    write_if_changed(render("(none -- placeholder)", ""))


def validate_names(names):
    """names: {label: ble_name}. Unique across the fleet, and short enough."""
    seen = {}
    for label, name in names.items():
        if not name:
            fail("assembly '%s' has an empty ble_name" % label)
        if len(name.encode("utf-8")) > BLE_NAME_MAX:
            fail(
                "assembly '%s' ble_name '%s' exceeds %d bytes (BLE scan response limit)"
                % (label, name, BLE_NAME_MAX)
            )
        if name in seen:
            fail(
                "duplicate BLE name '%s' for assemblies '%s' and '%s'"
                % (name, seen[name], label)
            )
        seen[name] = label


def main():
    if not os.path.isfile(BOARDS_FILE):
        fail("missing %s" % BOARDS_FILE)
    boards = read_known_boards()
    overrides = read_name_overrides()

    names = {label: overrides.get(label, label) for _, label in boards}
    # Overrides for assemblies not (yet) in known-boards.txt still count for
    # uniqueness: two assemblies must never advertise the same name.
    for label, name in overrides.items():
        names.setdefault(label, name)
    validate_names(names)

    label, reason = select_label(boards)
    if label is None:
        keep_or_placeholder(reason)
        return

    ble_name = names[label]
    write_if_changed(render(label, ble_name))
    print("gen_assembly_config: src/AssemblyConfig.h for %s (ble: %s)" % (label, ble_name))


main()
