# PlatformIO extra_script: embed the short git hash at build time.
#
# Writes src/telemetry/fw_version_autogen.h (gitignored). A header instead of a
# -D define on purpose: a changed define invalidates every object file, a
# changed header only rebuilds its includers. The file is rewritten only when
# the content differs, so unchanged builds stay fully incremental.
#
# FW_VERSION (semver + this hash) is composed in src/telemetry/telemetry.h and
# reported in every heartbeat event (PROJECT-PLAN.md §4.3).
import os
import subprocess

Import("env")  # noqa: F821 -- provided by PlatformIO/SCons

PROJECT_DIR = env["PROJECT_DIR"]  # noqa: F821
HEADER = os.path.join(PROJECT_DIR, "src", "telemetry", "fw_version_autogen.h")


def git_hash():
    try:
        h = (
            subprocess.check_output(
                ["git", "rev-parse", "--short=7", "HEAD"],
                cwd=PROJECT_DIR,
                stderr=subprocess.DEVNULL,
            )
            .decode()
            .strip()
        )
        dirty = (
            subprocess.call(
                ["git", "diff", "--quiet", "HEAD"],
                cwd=PROJECT_DIR,
                stderr=subprocess.DEVNULL,
            )
            != 0
        )
        return h + ("-dirty" if dirty else "")
    except Exception:
        return "nogit"


content = (
    "// Auto-generated by tools/git_version.py at build time. Do not edit;\n"
    "// gitignored. See src/telemetry/telemetry.h for FW_VERSION composition.\n"
    '#define FW_GIT_HASH "%s"\n' % git_hash()
)

previous = None
if os.path.isfile(HEADER):
    with open(HEADER) as f:
        previous = f.read()
if content != previous:
    os.makedirs(os.path.dirname(HEADER), exist_ok=True)
    with open(HEADER, "w") as f:
        f.write(content)
